### ISSUE TITLE
Multi instance monitoring

### ISSUE THREAD

**Issue by DanSman** [j6s/mailcow-exporter#5]
Hello :)

Any chance to get multi instances monitored?

**Comment by j6s** [comment]
I am a bit unsure what you mean - monitoring multiple mailcow instances with the same instance of `mailcow-exporter` should be possible by adding multiple targets for it in the prometheus configuration:

```yaml
scrape_configs:
  - job_name: 'mailcow-server-2'
    static_configs:
      - targets: [ 'mailcow_exporter:9099' ]
    params:
      host: [ 'mailcow-server-1.com' ]
      apiKey: [ 'YOUR-APIKEY-HERE' ]

  - job_name: 'mailcow-server-1'
    static_configs:
      - targets: [ 'mailcow_exporter:9099' ]
    params:
      host: [ 'mailcow-server-2.com' ]
      apiKey: [ 'YOUR-APIKEY-HERE' ]
```

I suspect however, that multi-instances refers to something else, that I am not familiar with. Could you provide a bit of additional information so I can read up on it?
